# Generated by Django 3.1.4 on 2021-01-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='classification',
            field=models.CharField(blank=True, choices=[('Flower', 'Flower'), ('Family', 'Family'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
