# Generated by Django 3.1.4 on 2020-12-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
