# Generated by Django 3.1.4 on 2020-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_flower_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='photo',
            field=models.ImageField(default='', upload_to='flower_photos'),
        ),
    ]
