# Generated by Django 3.1.4 on 2020-12-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_auto_20201214_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
