# Generated by Django 3.1.4 on 2020-12-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_auto_20201221_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='date',
            field=models.DateField(),
        ),
    ]
